### ISSUE TITLE
Not work hopper dropped items

### ISSUE THREAD

**Issue by andris155** [TacoSpigot/TacoSpigot#19]
![2016-03-26_19 45 00](https://cloud.githubusercontent.com/assets/8324198/14061844/4e7f092c-f38b-11e5-89a1-aaa7bc5108c2.png)
![2016-03-26_19 45 04](https://cloud.githubusercontent.com/assets/8324198/14061845/53ff2044-f38b-11e5-9d0e-3543d9504528.png)

**Comment by Techcable** [comment]
version?

**Comment by Techcable** [comment]
do you have push-based set to true or false?

**Comment by andris155** [comment]
![940b644e-f387-11e5-899a-48e2485aa94c](https://cloud.githubusercontent.com/assets/8324198/14062572/6eef8fec-f3a4-11e5-8c57-763403f01f68.PNG)

**Comment by andris155** [comment]
Taco.yml
```
config-version: 1
world-settings:
  default:
    verbose: true
    armor-stand:
      optimize-movement: true
    hopper:
      fire-InventoryMoveItemEvent: true
      push-based: true
    redstone-fire-BlockPhysicsEvent: false
```
