### ISSUE TITLE
Hoppers getting "stuck", ... on 1.8.8

### ISSUE THREAD

**Issue by L4BORG** [TacoSpigot/TacoSpigot#66]
Aside from changed mechanics (if you have 2 hoppers under 1 doublechest) hoppers would also get stuck and stop transferring items (until server restart) both issues would occur with push-based setting on or off.

Would it be possible to make "push-based: false" completely revert hopper behaviour (to paperspigot alike)?

**Comment by SnakeDaoust1232** [comment]
make sure you arent using trapped chests.

**Comment by L4BORG** [comment]
I did...

**Comment by Techcable** [comment]
Are you using `push-based`? Are there even more bugs with that?

**Comment by L4BORG** [comment]
Not really, those issues would happen without push-based set to true or false... overload load did seem to decrease after setting push-based to false.

Current config:

```
config-version: 1
useArraysForBlockStates: false
world-settings:
  default:
    verbose: false
    hopper:
      fire-InventoryMoveItemEvent: false
      push-based: false
    armor-stand:
      optimize-movement: false
    grass-ignores-light: true
    allow-non-player-entities-on-scoreboards: false
    redstone-fire-BlockPhysicsEvent: false
```

what really bothers me I guess is the fact that disabling push-based would default back to vanilla behaviour.
